arb-dir: lib/resources/strings
template-arb-file: app_ru.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/resources/strings
preferred-supported-locales:
  - ru
